/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_samples_fd_DetectionBasedTracker */

//#ifndef _Included_org_opencv_samples_fd_DetectionBasedTracker
//#define _Included_org_opencv_samples_fd_DetectionBasedTracker
#ifdef __cplusplus
extern "C" {
#endif



jboolean Java_com_example_hellojni_HelloCV_learn ( JNIEnv* env, jobject thiz , jstring dataSetPath , jstring fileName ,
		jstring dataMatrixName , jint noOfSubjects , jint noOfImages );

jint Java_com_example_hellojni_HelloCV_recognize1 ( JNIEnv* env, jobject thiz , jlong meanSubjects , jlong testFaceProject  );
jboolean Java_com_example_hellojni_HelloCV_project ( JNIEnv* env, jobject thiz , jlong meanData , jlong eigenVectors , jlong data2Project , jlong dest  );

jint Java_com_example_hellojni_HelloCV_recognize ( JNIEnv* env, jobject thiz , jstring fileName ,
		jstring dataMatrixName , jint noOfSubjects , jint noOfImages , jstring testCol  );

jboolean Java_com_example_hellojni_HelloCV_lbpDetector ( JNIEnv* env, jobject thiz , jstring tDataPath , jstring imgPath , jstring newImPath );
jboolean Java_com_example_hellojni_HelloCV_readData ( JNIEnv* env, jobject thiz , jstring fileName , jstring dataName , jlong dest );

jboolean Java_com_example_hellojni_HelloCV_subtract ( JNIEnv* env, jobject thiz , jlong src1 , jlong src2 , jlong dest );
jboolean Java_com_example_hellojni_HelloCV_multiply ( JNIEnv* env, jobject thiz , jlong src1 , jlong src2 , jlong dest );
#ifdef __cplusplus
}
#endif
//#endif
